# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EYE-Mate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EYE-Mate
  pod 'NMapsMap'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'Kingfisher', '~> 7.0'
end
